### ISSUE TITLE
"REST and OData API Documentation" - missing constraint (HATEOAS) and RMM

### ISSUE THREAD

**Issue by qmacro** [SAP-docs/api-style-guide#3]
In this style guide the [About REST APIs](https://help.sap.com/docs/SNG_4_APIDOC/53e39c8b7c924c28a2575be50bc09786/d8acc942e39d44af9231260bbb6a6161.html?locale=en-US#about-rest-apis) section talks about how an individual REST API is defined, listing various aspects. A fundamental aspect of REST, namely [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS), is missing from the list. While HATEOAS is a constraint normally found only in APIs that have attained [RMM level 3](https://martinfowler.com/articles/richardsonMaturityModel.html#level3) and many pragmatic RESTful APIs exist without implementing that constraint, don't you think that we should at least mention the Richardson Maturity Model and include a fundamental aspect of REST in this list, rather than exclude it (see https://www.youtube.com/watch?v=bhn-Dl87SDE for background)?

**Comment by Swisskaese** [comment]
Hi DJ, 
I am going to discuss this with Steffen Goebel in the API and Events CPA working group, which I am a member. My gut feeling is that we don't need to mention this, but let's see what they say.

**Comment by Swisskaese** [comment]
Hi, 
This is covered in an internal document that will be added to the public one very soon.

**Comment by qmacro** [comment]
Thanks, it will be good to see a complete description of REST in this section soon 👍
